language: csharp
solution: MassSpecFiles.sln
install:
  - nuget restore MassSpecFiles.sln
  - nuget install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=ReleaseAndTestNoThermo MassSpecFiles.sln 
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Test/bin/Release/Test.dll
